### ISSUE TITLE
Unable to install Hydra via Scoop 

### ISSUE THREAD

**Issue by maurice-freitag** [ory/scoop#1]
It's currently not possible to install Hydra via Scoop. The `hydra.json` files in both this repo and [scoop-hydra ](https://github.com/ory/scoop-hydra/) point to packages that don't exist (yet?): 
* scoop: https://github.com/ory/hydra/releases/download/v1.11.0-pre.0/hydra_1.11.0-pre.0-windows_32bit.zip)
* scoop-hydra: https://github.com/ory/hydra/releases/download/v1.10.7/hydra_1.10.7_windows_64bit.zip

The [latest release](https://github.com/ory/hydra/releases/) seems to be 1.10.6 which is not supported by both buckets. Would it be possible (& desired) to add older versions or at least 1.10.6 to one or both buckets? Haven't checked for products other than Hydra as of yet.

**Comment by aeneasr** [comment]
Thank you for the report, please see: https://github.com/ory/hydra/issues/2949

**Comment by aeneasr** [comment]
ps: that was fast :D

**Comment by maurice-freitag** [comment]
Oh wow, that reply came a lot faster than expected, ty :)
