### ISSUE TITLE
issue creating Ori account

### ISSUE THREAD

**Issue by Jeysee91** [ory/scoop#3]
Hello,

I am trying to create an ORY account, however it is not accepting my email address as an actual email. I tried multiple email addresses, none works.

error: 
Your account creation attempt failed. Please try again!

"<myemail>\r" is not valid "email"

Thank you for your help.

Regards,

**Comment by useEffects** [comment]
same here

**Comment by aeneasr** [comment]
Could you please provide the steps you performed to get to this result? I also assume this is on Windows? Looks like the carriage return is messing with the sign up

Are you using PowerShell or cmd.exe?
